name = "BLLacHostRecipe"
uuid = "be200d2e-71a8-4c15-87a1-7b745a5b9e99"
version = "0.1.0"
authors = ["Giorgio Calderone <giorgio.calderone@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
GModelFit = "ac42e6ba-c0bf-4fcf-827d-deea44b16255"
GModelFitViewer = "5d93b50e-5cc7-4feb-a740-ec85257caa01"
QSFit = "fea25315-b951-4667-83c9-50e53efab241"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
DataStructures = "0.18.22"
FITSIO = "0.17.5"
GModelFit = "0.4.0"
GModelFitViewer = "0.2.2"
QSFit = "0.3.1"
Statistics = "1.11.1"
